### ISSUE TITLE
[Database] Problem setting up a local database

### ISSUE THREAD

**Issue by neerajmalve** [BeWelcome/rox#97] opened 2019-03-13 18:53 UTC
I am trying to setup, having loads of issues. looks like Symfony library update issues and now some DB Structure issue.. eg:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bewelcome.user' doesn't exist. Have many ongoing issues. 

I am sure I am trying something wrong. else this should get installed one stroke. Do you have any updated document or Git Branch which I should try out?

Thanks
Neeraj

**Comment by thisismeonmounteverest** [comment] 2019-03-13 19:52
@neerajmalve the correct branch is bootstrap4. 

At which step in INSTALL do you have problems?

**Comment by neerajmalve** [comment] 2019-03-14 08:47
I have done all the steps. After installation I see these issues. 

http://46.249.199.59/_profiler/latest?panel=exception
http://46.249.199.59/login_check

**Comment by thisismeonmounteverest** [comment] 2019-03-15 06:14
@neerajmalve The preferences table has no content therefore the check for your preferred language fails. I add the necessary seeds tonight (CET).

**Comment by neerajmalve** [comment] 2019-03-15 16:03
Thanks! I will wait for the update :-)

**Comment by thisismeonmounteverest** [comment] 2019-03-15 23:51
@neerajmalve I just pushed the update. Please re-generate the database.

**Comment by neerajmalve** [comment] 2019-03-16 13:26
I dropped the DB, created empty one again and ran following steps, but no luck:


Initialize the database.

This generates a new database as given in the .env.* files and presets some data.

$ php bin/console doctrine:schema:create
$ php bin/console hautelook:fixtures:load

To get translated keywords update words and language tables to match the current translation on the site

$ wget http://downloads.bewelcome.org/for_developers/rox_test_db/languages.sql.bz2
$ wget http://downloads.bewelcome.org/for_developers/rox_test_db/words.sql.bz2
$ bunzip2 languages.sql.bz2 words.sql.bz2
$ mysql bewelcome -u bewelcome -pbewelcome < languages.sql
$ mysql bewelcome -u bewelcome -pbewelcome < words.sql

**Comment by thisismeonmounteverest** [comment] 2019-03-16 17:46
@neerajmalve As you dropped the database you need to recreate it before running the commands:

$php bin/console doctrine:database:create

(or follow the instructions in INSTALL.md again to create the DB with matching rights).

**Comment by neerajmalve** [comment] 2019-03-17 09:04
Yes as I mentioned in the first line: I dropped the DB, created empty one again and ran following steps, but no luck:

I followed all steps as per INSTALL.md

**Comment by neerajmalve** [comment] 2019-03-17 09:05
mysql> show tables;
+--------------------------+
| Tables_in_bewelcome      |
+--------------------------+
| activities               |
| activitiesattendees      |
| comments                 |
| community_news           |
| community_news_comment   |
| cryptedfields            |
| donations                |
| ewiki                    |
| faq                      |
| faqcategories            |
| feedbackcategories       |
| feedbacks                |
| forums_posts             |
| forums_threads           |
| gallery                  |
| gallery_items            |
| geonames                 |
| geonames_admincodes      |
| geonamesadminunits       |
| geonamesalternatenames   |
| geonamescountries        |
| group_membership_trads   |
| groups                   |
| groups_trads             |
| hosting_eagerness_slider |
| languages                |
| logs                     |
| members                  |
| membersgroups            |
| memberslanguageslevel    |
| membersphotos            |
| memberspreferences       |
| memberstrads             |
| messages                 |
| notes                    |
| params                   |
| preferences              |
| request                  |
| rights                   |
| rightsvolunteers         |
| sub_trips                |
| subject                  |
| trips                    |
| words                    |
+--------------------------+
44 rows in set (0.01 sec)

**Comment by thisismeonmounteverest** [comment] 2019-03-17 09:05
@neerajmalve Sorry I missed that part.
Database tables look correct. What issue do you have?

**Comment by neerajmalve** [comment] 2019-03-18 09:25
You will notice the errors when you login to http://46.249.199.59/login_check using default login. 
Argument 1 passed to App\Entity\Member::getMemberPreferenceValue() must be an instance of App\Entity\Preference, null given, called in /var/www/rox/src/EventListener/UserLocaleListener.php on line 56

**Comment by thisismeonmounteverest** [comment] 2019-03-18 19:24
@neerajmalve That is still the same error.

Could you please check if preferences table has some entries?

**Comment by neerajmalve** [comment] 2019-03-22 06:19
I didnt find the table entries and i have populated them from another installation. and now here is the new error:
In the lauguages table id 2 entry was missing, I have added a dummy entry for now. 
few pages like http://46.249.199.59/community & http://46.249.199.59/volunteer still has a new error now.

**Comment by neerajmalve** [comment] 2019-03-22 06:28
by the way @thisismeonmounteverest,  appreciate all help you are providing..

**Comment by thisismeonmounteverest** [comment] 2019-03-22 19:39
@neerajmalve The new errors you see are due to short_open_tag set to Off. Please change that to On.
That's a bit hidden in the INSTALL (* PHP short opening tags enabled).

Some pages won't work though as they rely on old tables being there that are not created when using the doctrine approach.

To familiarize yourself with the code focus on stuff in src/ and templates/

**Comment by neerajmalve** [comment] 2019-03-28 13:46
Sorry for the delay in reply. I have fixed the short code issue and there are quite a few errors still on the way. Is this require a fix? Is it just me who is finding difficulty with the install? If may be I am doing something wrong? For example: http://46.249.199.59/newsletters and http://46.249.199.59/search/members

**Comment by thisismeonmounteverest** [comment] 2019-03-28 19:00
@neerajmalve You're quite good at finding the problematic pages that do not work with the doctrine approach yet :) Therefore no fixes are necessary (except adding a matching entity and fixture to populate the database).
For the first link the issue is that the broadcast table is a legacy one. The second issue is side effect of the missing language id you mentioned.

If you want to make your life easier you can download the test database (which contains old tables as well): https://downloads.bewelcome.org/for_developers/rox_test_db/bewelcome.sql.bz2

To deploy: Unzip the file and import it into your database with

mysql -ubewelcome -pbewelcome < bewelcome.sql

After that you will need to run all migration scripts with

vendor/bin/phinx migrate

After that you should be able to access the whole site.

**Comment by thisismeonmounteverest** [comment] 2019-03-28 19:02
Alternatively if you're familiar with Doctrine you could add an Entity in src/Doctrine/Broadcast.php for the broadcast table based on Rox/Storage/Broadcast.php to get past the problem behind newsletters.

**Comment by thisismeonmounteverest** [comment] 2019-05-08 18:37
@neerajmalve: I see that creating the database based on Doctrine is a big hurdle and the test database is too big. What would you prefer: A smaller test database or a Doctrine created database that actually works for all pages.

**Comment by amnesiac84** [comment] 2019-09-14 08:36
I assume this issue has been fixed or not longer relevant? It will be closed if there's no reaction soon

**Comment by crumbking** [comment] 2020-06-01 18:57
Closing. The database is not perfect yet. But with the recent improvements in #138 and #148

**Closed by crumbking** 2020-06-01 18:57 UTC
Labels: help wanted, question

**Comment by gboniscontro** [comment] 2021-05-20 22:14
i have this error when I try to do something in the database h Error 'An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_get  
  addresses: getaddrinfo failed:
