### ISSUE TITLE
today's update made the profile pictures disapear

### ISSUE THREAD

**Issue by perkelix** [BeWelcome/rox#141] opened 2020-05-23 15:22 UTC
The update that was pushed 3 hours ago made the profile pictures disappear. Reloading the page doesn't fix it. 
![Kuvakaappaus - 2020-05-23 18-21-40](https://user-images.githubusercontent.com/57731134/82734238-52186200-9d22-11ea-8e4c-2e1e78d79999.png)

**Comment by thisismeonmounteverest** [comment] 2020-05-23 19:09
@perkelix: We had similar reports on the site as well. Could you please logout and login again?

I see your profile picture.

**Comment by amnesiac84** [comment] 2020-05-23 20:39
logging out and in worked for me!

**Comment by perkelix** [comment] 2020-05-24 10:52
Yup. Logging in and out worked. It would still be a good idea to track down what causes this.

**Comment by thisismeonmounteverest** [comment] 2020-05-25 09:55
I'm pretty sure it is the session invalidation that happened on cache clear on the deploys. I moved the sessions to the database so this should not happen anymore.

**Comment by thisismeonmounteverest** [comment] 2020-05-26 09:02
Found that there is another factor at play. The avatar images are only served when fully authenticated and not already when using the remember me functionality.

**Comment by thisismeonmounteverest** [comment] 2020-06-01 06:57
fixed on beta.

**Comment by crumbking** [comment] 2020-06-19 18:26
Seems to be fixed. I could not reproduce it anymore.

**Closed by crumbking** 2020-06-19 18:26 UTC
Labels: bug, test on beta
